### ISSUE TITLE
安装了 openwrt-ipq807x-glinet_ax1800-squashfs-sysupgrade.tar 后路由器界面打不开了

### ISSUE THREAD

**Issue by frankrx41** [JiaY-shi/build-gl.inet#1]
安装的版本是 https://github.com/JiaY-shi/build-gl.inet/releases/download/2022.08.02-0942/openwrt-ipq807x-glinet_ax1800-squashfs-sysupgrade.tar

从 [zzz-default-settings](https://github.com/JiaY-shi/build-gl.inet/blob/master/custom/default-settings/files/zzz-default-settings) 文件里面是找到 ip 地址被改成了 192.168.0.1
但是浏览器访问 192.168.0.1 后显示的是 404

请问要怎么配置

**Comment by JiaY-shi** [comment]
192.168.8.1能访问么？我忘记我编译的时候是否包含官方UI了
