### ISSUE TITLE
action编译时会因空间不足导致编译失败

### ISSUE THREAD

**Issue by XIAOZHAOXSXH** [JiaY-shi/build-gl.inet#5]
抱歉占用一个issue
最近编译时经常碰见这个情况
This step has been truncated due to its large size. Download the full logs from the menu once the workflow run has completed. 
action应该有84g的空间，不知为何空间不足，请问有没有解决办法

**Comment by JiaY-shi** [comment]
这个不影响呢，这个是日志太大了被截断了。
